name: meld_classifier
channels:
  - defaults
  - pog87
  - conda-forge
dependencies:
  - python=3.8
  - tensorflow=2.5
  - pytest=6.2
  - nibabel=3.2
  - pillow=8.4
  - jupyterlab=3.2
  - ptitprince=0.2
  - scikit-image=0.18
  - h5py=3.1
  - fpdf=1.7
  - pip=21.2
  - pip:
    - matplotlib_surface_plotting
    - potpourri3d==0.0.4
#    - umap-learn
    - nilearn==0.8
    - neuroCombat==0.2.12
    - alibi==0.6
    - patsy==0.5.2
    - matplotlib==3.5.1
    - torch==1.12
    - torchvision==0.13
    - SimpleITK==2.1.1
    - git+https://github.com/Deep-MI/LaPy.git
