name: meld_classifier
channels:
  - defaults
  - pog87
  - conda-forge
dependencies:
  - python=3.7
  - tensorflow=2.6
  - pytest=6.2
  - nibabel=3.2
  - pillow=8.4
  - jupyterlab=3.2
  - ptitprince=0.2
  - scikit-image=0.18
  - h5py=3.1
  - fpdf=1.7
  - pip=21.2
  - pip:
    - matplotlib_surface_plotting
    - potpourri3d==0.0.4
#    - umap-learn
    - nilearn==0.8
    - git+https://github.com/kwagstyl/neuroCombat.git@estimates_shrink
    - alibi==0.6
    - matplotlib
